# Generated by Django 5.1 on 2024-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('season', models.CharField(max_length=200)),
            ],
        ),
    ]
