# Generated by Django 5.1 on 2024-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='continente',
            field=models.CharField(choices=[('Europa', 'Europa'), ('America del Nord', 'America del Nord'), ('America del Sud', 'America del Sud'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('Antartide', 'Antartide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='durata',
            field=models.CharField(choices=[('Weekend Lungo (2-4 Giorni)', 'Weekend Lungo (2-4 Giorni)'), ('1 Settimana', '1 Settimana'), ('2 Settimane', '2 Settimane'), ('3 settimane o più', '3 settimane o più')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='periodo',
            field=models.CharField(choices=[('Inverno', 'Inverno'), ('Primavera', 'Primavera'), ('Estate', 'Estate'), ('Autunno', 'Autunno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='prezzo',
            field=models.CharField(choices=[('Viaggio Low Cost', 'Viaggio Low Cost'), ('Budget Medio', 'Budget Medio'), ('Viaggio di Lusso', 'Viaggio di Lusso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='tipologia',
            field=models.CharField(choices=[('Culturale', 'Culturale'), ('Relax', 'Relax'), ('Enogastronomico', 'Enogastronomico'), ('On The Road', 'On The Road'), ('Avventura', 'Avventura')], max_length=50),
        ),
    ]
