# Generated by Django 5.1 on 2024-08-22 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='duration',
            field=models.CharField(choices=[('<SETT', 'Meno di una settimana'), ('12SETT', '1/2 Settimane'), ('3SETT', '3 Settimane'), ('>3SETT', 'Più di 3 settimane')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='price',
            field=models.CharField(choices=[('€', 'Economica'), ('€€', 'Costosa'), ('€€€', 'Lusso')], max_length=3),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='season',
            field=models.CharField(choices=[('INV', 'Inverno'), ('PRI', 'Primavera'), ('EST', 'Estate'), ('AUT', 'Autunno')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='type',
            field=models.CharField(choices=[('BEACH', 'Beach'), ('MOUNTAIN', 'Mountain'), ('CITY', 'City'), ('CRUISE', 'Cruise'), ('ADVENTURE', 'Adventure')], max_length=20),
        ),
        migrations.CreateModel(
            name='VacationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('DONE', 'Done')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vacation', models.ManyToManyField(related_name='list', to='vacation.vacation')),
            ],
        ),
    ]
